### ISSUE TITLE
Questions about computing metrics(mIoU)?

### ISSUE THREAD

**Issue by kellyiss** [dingjiansw101/ZegFormer#14]
Thanks for your amazing work.
I have some questions:
1. When computing the IoU in evaluation, is the background label (255) ignored?
2. If during testing, the "no-object" class scores are ignored, then how to obtain the background mask?  Without background mask, every pixel will be assigned an object word. I just run the demo code find there's no background class.

**Comment by dingjiansw101** [comment]
Actually, the background is not accurate. Some stuff classes belong to the background.
1. Yes, the 255 labels are ignored.
2. The "no-object" class is also ignored during testing. So there is no mask prediction for the "no-object" class.
