### ISSUE TITLE
how to get word_vectors files?

### ISSUE THREAD

**Issue by wly-ai-bj** [dingjiansw101/ZegFormer#5]
In the file of README.md ，the part of "Expected data structure", how to get word_vectors files of *.pkl？？？

**Comment by dingjiansw101** [comment]
Hi, I uploaded the *.pkl. https://github.com/dingjiansw101/ZegFormer/tree/main/datasets/coco/coco_stuff/word_vectors
These files are downloaded from https://github.com/subhc/SPNet/tree/master/data/datasets/cocostuff/word_vectors
These files are traditional word embeddings, which are just used for ablation. We do not recommand to use them.

**Comment by dingjiansw101** [comment]
Since it it not active for several days, I am closing the issue. Feel free to re-open issues or propose new issues, if you have more questions.
