### ISSUE TITLE
Request for release of Pascal VOC configs and preprocessing

### ISSUE THREAD

**Issue by mustafa1728** [dingjiansw101/ZegFormer#8]
Hello authors, thank you for this great work!

I was trying to run Zegformer on Pascal VOC, but was facing some problems. I was wondering if you can release the configs and data preprocessing required to reproduce the results on this dataset reported in the paper. Would help a lot!

Thank you.

**Comment by zichengsaber** [comment]
Same questions

**Comment by dingjiansw101** [comment]
Hi, I will release it soon. You can also send me email to obtain the codes.

**Comment by dingjiansw101** [comment]
Hey guys, I have updated the code for voc. If you have any problems, please let me know.
